VolunterSite.WebUI/VolunteerSite.WebUI/ViewModels/JobListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VolunteerSite.Domain.Models;

namespace VolunteerSite.WebUI.ViewModels
{
    public class JobListViewModel
    {
        public ICollection<JobListing> JobListings { get; set; }

        public Organization Organization { get; set; }
    }
}

VolunterSite.WebUI/VolunteerSite.WebUI/Controllers/VolunteerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using VolunteerSite.Data.Context;
using VolunteerSite.Domain.Models;
using VolunteerSite.Service.Services;
using VolunteerSite.WebUI.ViewModels;

namespace VolunteerSite.WebUI.Controllers
{
    
    public class VolunteerController : Controller
    {
        private readonly IVolunteerService _volunteerService;
        private readonly IJobListingService _jobListingService;
        private readonly UserManager<AppUser> _userManager;

        public VolunteerController(IVolunteerService volunteerService,
            IJobListingService jobListingService,
            UserManager<AppUser> userManager)
        {
            _volunteerService = volunteerService;
            _jobListingService = jobListingService;
            _userManager = userManager;
        }
        [HttpGet]
        public IActionResult Profile() => View();
        [HttpPost]
        public IActionResult Profile(VolunteerEditViewModel vm)
        {
            Volunteer newVolunteer = vm.Volunteer;
            newVolunteer = new Volunteer
            {
                UserId = _userManager.GetUserId(User)
            };
            _volunteerService.Create(newVolunteer);

            return RedirectToAction("Index","Home");
        }
   
        public IActionResult JobList()
        {
            ICollection<JobListing> jobListings;
            jobListings = _jobListingService.GetAll();
            return View(jobListings);
        }
        [HttpPost]
        public IActionResult JoinJob(JoinJobViewModel vm)
        {
            JobListing selectedjobListing = vm.JobListing;
            Volunteer currentUser = _volunteerService.GetByUserId(_userManager.GetUserId(User));
            selectedjobListing.Volunteers.Add(currentUser);

            return View();
        }
    }
}

VolunterSite.WebUI/VolunteerSite.WebUI/Views/Volunteer/CreateProfile.cshtml
@model CreateVolunteerViewModel

<h1>Create Profile</h1>
<div class="container">
    <form asp-action="CreateProfile" method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label asp-for="Volunteer.FirstName"></label>
            <input class="form-control" asp-for="Volunteer.FirstName" />
        </div>
        <div class="form-group">
            <label asp-for="Volunteer.LastName"></label>
            <input class="form-control" asp-for="Volunteer.LastName" />
        </div>
        <div class="form-group">
            <label asp-for="Volunteer.Email"></label>
            <input class="form-control" asp-for="Volunteer.Email" />
        </div>
        <div class="form-group">
            <label asp-for="Volunteer.PhoneNumber"></label>
            <input class="form-control" asp-for="Volunteer.PhoneNumber" />
        </div>
        <div class="form-group">
            <label asp-for="Volunteer.SkillsAndExperience"></label>
            <textarea class="form-control" rows="5" id="comment" asp-for="Volunteer.SkillsAndExperience"></textarea>
        </div>
        <div class="form-group">
            <label asp-for="Image"></label>
            <input type="file" accept=".jpg" class="form-control-file" asp-for="Image" />
        </div>
        <button type="submit" class="btn btn-primary">submit</button>
    </form>
</div>

VolunterSite.WebUI/VolunteerSite.WebUI/Views/Volunteer/Details.cshtml
@model JobDetailsViewModel
@{
    ViewData["Title"] = "JobDetails";
}

<img src="@Model.Organization.LogoImageURL" alt="company Logo" class="logo">

<h2>@Model.JobListing.TypeOfJob</h2>
<br />
<p>@Model.Organization.CompanyName • @Model.JobListing.Address, @Model.JobListing.City, @Model.JobListing.State</p>
<p>@Model.JobListing.Date</p>

<h3>Job Description</h3>

<p>@Model.JobListing.Description</p>

VolunterSite.WebUI/VolunteerSite.WebUI/Views/Volunteer/EditProfile.cshtml
@model VolunteerEditViewModel

@{
    ViewData["Title"] = "EditProfile";
}

<h1>EditProfile</h1>
<hr />
<div class="container">
    <div>
        <form asp-action="EditProfile" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SkillsAndExperience" class="control-label"></label>
                <input asp-for="SkillsAndExperience" class="form-control" />
                <span asp-validation-for="SkillsAndExperience" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image"></label>
                <input type="file" accept=".jpg" class="form-control-file" asp-for="Image" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Profile">Back to Profile</a>
</div>

VolunterSite.WebUI/VolunteerSite.WebUI/Views/Volunteer/Index.cshtml
@model Volunteer
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<div>
    @if (User.Identity.IsAuthenticated)
    {
    <p>Welcome to the site! - @User.Identity.Name</p>
    }
</div>

VolunterSite.WebUI/VolunteerSite.WebUI/Views/Volunteer/JobList.cshtml
@model ICollection<JobListing>


<h1>JobList</h1>
<div>
    <table class="table table-dark">
        <tr>
            <th>Type Of Job</th>
            <th>Date</th>
            <th>Description</th>
            <th>Address</th>
            <th>City</th>
            <th>State</th>
            <th>Positions Available</th>
        </tr>

        @foreach (var j in Model)
        {
            <tr>
                <td>@j.TypeOfJob</td>
                <td>@j.Date</td>
                <td>@j.Description</td>
                <td>@j.Address</td>
                <td>@j.City</td>
                <td>@j.State</td>
                <td>@j.PositionsAvailable</td>
                @*<td>
                        <form method="post" asp-controller="Volunteer" asp-action="JoinJob">
                            <input type="submit" value="Volunteer" />
                        </form>
                    </td>*@

            </tr>
        }

    </table>
</div>

VolunterSite.WebUI/VolunteerSite.WebUI/Views/Volunteer/Profile.cshtml
@model VolunteerEditViewModel

<h1>Edit Profile</h1>

<form asp-action="Profile" method="post">
    <div class="form-group">
        <label asp-for="Volunteer.FirstName"></label>
        <input class="form-control" asp-for="Volunteer.FirstName" />
    </div>
    <div class="form-group">
        <label asp-for="Volunteer.LastName"></label>
        <input class="form-control" asp-for="Volunteer.LastName" />
    </div>
    <div class="form-group">
        <label asp-for="Volunteer.Email"></label>
        <input class="form-control" asp-for="Volunteer.Email" />
    </div>
    <div class="form-group">
        <label asp-for="Volunteer.SkillsAndExperience"></label>
        <input class="form-control" asp-for="Volunteer.SkillsAndExperience" />
    </div>
    <button type="submit" class="btn btn-primary">submit</button>
</form>

VolunterSite.WebUI/VolunteerSite.WebUI/Views/Volunteer/TrackedJobs.cshtml
@model IEnumerable<JobListing>
@{
    ViewData["Title"] = "TrackedJobs";
}

<h1>TrackedJobs</h1>
<table class="table table-bordered">
    @foreach (var j in Model)
    {
        <tr>
            <td>@j.TypeOfJob</td>
            <td> @Html.ActionLink("Details", "Details", new { id = j.Id }, new { @class = "btn btn-primary" }) @Html.ActionLink("Leave", "LeaveJob", new { id = j.Id }, new { @class = "btn btn-primary" })</td>
        </tr>
    }

</table>